# Generated by Django 5.2.6 on 2025-10-08 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('pymetanalis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubida',
            options={'ordering': ['-fecha_subida']},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AlterModelOptions(
            name='historialarticulo',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='articulo',
            name='archivo_subida',
            field=models.ForeignKey(blank=True, help_text='Archivo .bib del que proviene este artículo. Si es null, es un artículo manual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulos.archivosubida'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='bibtex_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ELIMINACION', 'Eliminación'), ('DESCARGA', 'Descarga')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('proyecto', 'bibtex_key')},
        ),
    ]
