# Generated by Django 5.2.6 on 2025-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_archivosubida_options_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubida',
            options={},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialarticulo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='bibtex_key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='archivo_subida',
        ),
    ]
