# Generated by Django 5.2.6 on 2025-10-09 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_archivosubida_options_alter_articulo_options_and_more'),
        ('pymetanalis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubida',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Archivo Subido', 'verbose_name_plural': 'Archivos Subidos'},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='historialarticulo',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de Artículo', 'verbose_name_plural': 'Historiales de Artículos'},
        ),
        migrations.RenameField(
            model_name='historialarticulo',
            old_name='fecha',
            new_name='fecha_cambio',
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('proyecto', 'bibtex_key')},
        ),
        migrations.RemoveField(
            model_name='historialarticulo',
            name='campo_modificado',
        ),
        migrations.AddField(
            model_name='archivosubida',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulo',
            name='archivo_bib',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='archivosubida',
            name='ruta_archivo',
            field=models.FileField(upload_to='archivos_bib/'),
        ),
        migrations.AlterField(
            model_name='archivosubida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='bibtex_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usuario_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('DESCARGA', 'Descarga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='articulo_original',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
    ]
