# Generated by Django 5.2.6 on 2025-10-09 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_archivosubida_options_alter_articulo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubida',
            options={},
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialarticulo',
            options={},
        ),
        migrations.RenameField(
            model_name='historialarticulo',
            old_name='fecha_cambio',
            new_name='fecha',
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='archivosubida',
            name='visualizado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='articulo_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='articulos.articulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='historialarticulo',
            name='campo_modificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivosubida',
            name='ruta_archivo',
            field=models.FileField(upload_to='uploads/articulos/'),
        ),
        migrations.AlterField(
            model_name='archivosubida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='bibtex_key',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='usuario_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='archivo_bib',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_actualizacion',
        ),
    ]
