# Generated by Django 5.2.6 on 2025-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_archivosubida_options_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='archivo_bib',
            field=models.CharField(blank=True, help_text='Nombre del archivo .bib de origen', max_length=255, null=True),
        ),
    ]
