# Generated by Django 5.2.6 on 2025-10-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_articulo_archivo_bib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='archivo_bib',
        ),
    ]
