# Generated by Django 5.2.6 on 2025-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_remove_articulo_archivo_bib'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='archivo_bib',
            field=models.CharField(blank=True, help_text='Nombre del archivo .bib de origen', max_length=255, null=True),
        ),
    ]
