# Generated by Django 5.2.6 on 2025-10-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_asignacioncampo_campometanalisis_plantillabusqueda_and_more'),
        ('pymetanalis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubida',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Archivo Subido', 'verbose_name_plural': 'Archivos Subidos'},
        ),
        migrations.AlterModelOptions(
            name='historialarticulo',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de Artículo', 'verbose_name_plural': 'Historial de Artículos'},
        ),
        migrations.RenameField(
            model_name='historialarticulo',
            old_name='fecha',
            new_name='fecha_cambio',
        ),
        migrations.RemoveField(
            model_name='asignacioncampo',
            name='valor',
        ),
        migrations.AddField(
            model_name='articulo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asignacioncampo',
            name='valor_encontrado',
            field=models.TextField(blank=True, help_text='Valor encontrado por el colaborador', null=True),
        ),
        migrations.AddField(
            model_name='historialarticulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación de Tarea'), ('MODIFICACION', 'Modificación'), ('DESCARGA', 'Descarga'), ('ELIMINACION', 'Eliminación'), ('ENVIO_REVISION', 'Envío a Revisión'), ('APROBACION', 'Aprobación'), ('CORRECCION_SOLICITADA', 'Corrección Solicitada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_articulos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['fecha_modificacion'], name='articulos_a_fecha_m_acecfc_idx'),
        ),
        migrations.AddIndex(
            model_name='historialarticulo',
            index=models.Index(fields=['articulo', '-fecha_cambio'], name='articulos_h_articul_b05e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='historialarticulo',
            index=models.Index(fields=['tipo_cambio'], name='articulos_h_tipo_ca_985450_idx'),
        ),
    ]
