# Generated by Django 5.2.6 on 2025-10-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_alter_archivosubida_options_and_more'),
        ('pymetanalis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo_accion', models.CharField(choices=[('APROBADO', 'Aprobado'), ('CORRECCION', 'Corrección Solicitada')], max_length=20)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False, help_text='Si el colaborador ya vio el comentario')),
            ],
            options={
                'verbose_name': 'Comentario de Revisión',
                'verbose_name_plural': 'Comentarios de Revisión',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.AlterModelOptions(
            name='plantillabusqueda',
            options={'ordering': ['-es_predeterminada', 'nombre'], 'verbose_name': 'Plantilla de Búsqueda', 'verbose_name_plural': 'Plantillas de Búsqueda'},
        ),
        migrations.RemoveIndex(
            model_name='articulo',
            name='articulos_a_fecha_m_acecfc_idx',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha_modificacion',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='asignacioncampo',
            old_name='valor_encontrado',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='comentarios_revision',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='datos_extraidos',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='revisado_por',
        ),
        migrations.RemoveField(
            model_name='historialarticulo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación de Tarea'), ('MODIFICACION', 'Modificación'), ('DESCARGA', 'Descarga'), ('ELIMINACION', 'Eliminación'), ('ENVIO_REVISION', 'Envío a Revisión'), ('APROBACION', 'Aprobación'), ('SOLICITUD_CORRECCION', 'Corrección Solicitada')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='archivosubida',
            index=models.Index(fields=['proyecto', '-fecha_subida'], name='articulos_a_proyect_e29b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['fecha_actualizacion'], name='articulos_a_fecha_a_8d901e_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['bibtex_key'], name='articulos_a_bibtex__1d13b5_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncampo',
            index=models.Index(fields=['articulo', 'completado'], name='articulos_a_articul_cae38f_idx'),
        ),
        migrations.AddIndex(
            model_name='campometanalisis',
            index=models.Index(fields=['proyecto'], name='articulos_c_proyect_ace956_idx'),
        ),
        migrations.AddIndex(
            model_name='historialarticulo',
            index=models.Index(fields=['usuario', '-fecha_cambio'], name='articulos_h_usuario_b2021b_idx'),
        ),
        migrations.AddField(
            model_name='comentariorevision',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_revision', to='articulos.articulo'),
        ),
        migrations.AddField(
            model_name='comentariorevision',
            name='colaborador',
            field=models.ForeignKey(help_text='Colaborador que recibe el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariorevision',
            name='supervisor',
            field=models.ForeignKey(help_text='Supervisor que hizo el comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_dados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comentariorevision',
            index=models.Index(fields=['articulo', '-fecha_comentario'], name='articulos_c_articul_8cca8b_idx'),
        ),
        migrations.AddIndex(
            model_name='comentariorevision',
            index=models.Index(fields=['colaborador', 'leido'], name='articulos_c_colabor_8ebbbf_idx'),
        ),
    ]
