# Generated by Django 5.2.6 on 2025-10-13 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_comentariorevision_alter_plantillabusqueda_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncampo',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Si este campo específico fue aprobado por un supervisor'),
        ),
        migrations.AddField(
            model_name='asignacioncampo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que aprobó este campo específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacioncampo',
            name='fecha_aprobacion_campo',
            field=models.DateTimeField(blank=True, help_text='Cuándo fue aprobado este campo', null=True),
        ),
    ]
