# Generated by Django 4.2 on 2025-10-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_asignacioncampo_aprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivosubida',
            name='ruta_archivo',
        ),
    ]
