# Generated by Django 5.2.6 on 2025-10-22 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_remove_archivosubida_ruta_archivo'),
        ('pymetanalis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo se asignaron tareas (ahora automático al crear)', null=True),
        ),
        migrations.AlterField(
            model_name='campometanalisis',
            name='tipo_dato',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('FECHA', 'Fecha'), ('SI_NO', 'Sí/No'), ('OPCIONES', 'Opciones múltiples')], default='TEXTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialarticulo',
            name='tipo_cambio',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION_METADATA', 'Edición de Metadata'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('ASIGNACION', 'Asignación de Tarea'), ('ASIGNACION_CAMPOS', 'Asignación de Campos'), ('DESASIGNACION_CAMPOS', 'Desasignación de Campos'), ('DESASIGNACION_CAMPO_INDIVIDUAL', 'Desasignación Individual'), ('MODIFICACION', 'Modificación'), ('DESCARGA', 'Descarga'), ('ELIMINACION', 'Eliminación'), ('ENVIO_REVISION', 'Envío a Revisión'), ('APROBACION', 'Aprobación'), ('SOLICITUD_CORRECCION', 'Corrección Solicitada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plantillabusqueda',
            name='es_predeterminada',
            field=models.BooleanField(default=True, help_text='Plantilla principal del proyecto (solo puede haber una)'),
        ),
        migrations.AddConstraint(
            model_name='plantillabusqueda',
            constraint=models.UniqueConstraint(condition=models.Q(('es_predeterminada', True)), fields=('proyecto', 'es_predeterminada'), name='una_plantilla_predeterminada_por_proyecto'),
        ),
    ]
