# Generated by Django 5.2.8 on 2026-02-25 15:35

import articulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_alter_articulo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF del artículo guardado automáticamente desde DOI', null=True, upload_to=articulos.models.upload_pdf_to),
        ),
    ]
