# Generated by Django 5.2.8 on 2026-02-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0015_analisisarticulo'),
        ('articulos', '0015_articulo_archivo_pdf'),
    ]

    operations = [
    ]
