# Generated by Django 5.2.8 on 2026-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0016_merge_0015_analisisarticulo_0015_articulo_archivo_pdf'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analisisarticulo',
            new_name='articulos_a_articul_ed22b3_idx',
            old_name='articulos_a_articul_idx',
        ),
        migrations.RenameIndex(
            model_name='analisisarticulo',
            new_name='articulos_a_proyect_1d524a_idx',
            old_name='articulos_a_proyec_idx',
        ),
        migrations.RenameIndex(
            model_name='analisisarticulo',
            new_name='articulos_a_estado_20def3_idx',
            old_name='articulos_a_estado_idx',
        ),
        migrations.AlterField(
            model_name='analisisarticulo',
            name='mensaje_error',
            field=models.TextField(blank=True, help_text='Mensaje de error si algo falló', null=True),
        ),
    ]
