# Generated by Django 5.2.8 on 2026-02-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0015_articulo_open_access'),
        ('articulos', '0017_rename_articulos_a_articul_idx_articulos_a_articul_ed22b3_idx_and_more'),
    ]

    operations = [
    ]
