# Generated by Django 5.2.6 on 2025-10-08 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('SALUD', 'Salud'), ('TECNOLOGIA', 'Tecnología'), ('EDUCACION', 'Educación'), ('CIENCIAS_SOCIALES', 'Ciencias Sociales'), ('INGENIERIA', 'Ingeniería')], default='SALUD', max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('configuracion', models.JSONField(blank=True, null=True)),
                ('total_articulos', models.IntegerField(default=0)),
                ('articulos_trabajados', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='pymetanalis.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('UNIRSE', 'Solicitud para unirse'), ('CAMBIO_ROL', 'Solicitud de cambio de rol')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='pymetanalis.proyecto')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Proyecto',
                'verbose_name_plural': 'Solicitudes Proyectos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_articulos', models.IntegerField(default=0)),
                ('articulos_aprobados', models.IntegerField(default=0)),
                ('promedio_calidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='pymetanalis.proyecto')),
            ],
            options={
                'verbose_name': 'Estadística Proyecto',
                'verbose_name_plural': 'Estadísticas Proyectos',
                'ordering': ['-fecha'],
                'unique_together': {('proyecto', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_aceptada', 'Solicitud Aceptada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('invitacion_proyecto', 'Invitación a Proyecto'), ('nueva_solicitud', 'Nueva Solicitud'), ('cambio_rol', 'Cambio de Rol'), ('general', 'General')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pymetanalis.proyecto')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pymetanalis.solicitudproyecto')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-fecha_creacion'], name='pymetanalis_usuario_c57a80_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_proyecto', models.CharField(choices=[('DUEÑO', 'Dueño'), ('SUPERVISOR', 'Supervisor'), ('COLABORADOR', 'Colaborador')], max_length=20)),
                ('fecha_incorporacion', models.DateTimeField(auto_now_add=True)),
                ('puede_invitar', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_proyectos', to='pymetanalis.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Proyecto',
                'verbose_name_plural': 'Usuarios Proyectos',
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
    ]
